const STORAGE_KEY="my-money-records";
const form=document.querySelector("#entry-form"),amountInput=document.querySelector("#amount"),categoryInput=document.querySelector("#category"),dateInput=document.querySelector("#date"),dateDisplay=document.querySelector("#date-display"),noteInput=document.querySelector("#note"),list=document.querySelector("#record-list"),emptyState=document.querySelector("#empty-state"),clearButton=document.querySelector("#clear-all"),typeButtons=[...document.querySelectorAll(".type-button")];
let entryType="expense",records=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");
const today=new Date(),localDate=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);
dateInput.value=localDate;document.querySelector("#today").textContent=new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(today);
function updateDateDisplay(){const[,month,day]=dateInput.value.split("-");dateDisplay.textContent=month&&day?`${month}/${day}`:"选择日期"}
dateInput.addEventListener("change",updateDateDisplay);updateDateDisplay();
const money=value=>`¥${Number(value).toFixed(2)}`;
function saveAndRender(){localStorage.setItem(STORAGE_KEY,JSON.stringify(records));render()}
function render(){const month=localDate.slice(0,7),monthly=records.filter(r=>r.date.startsWith(month)),income=monthly.filter(r=>r.type==="income").reduce((s,r)=>s+r.amount,0),expense=monthly.filter(r=>r.type==="expense").reduce((s,r)=>s+r.amount,0);document.querySelector("#total-income").textContent=money(income);document.querySelector("#total-expense").textContent=money(expense);document.querySelector("#balance").textContent=money(income-expense);list.replaceChildren();[...records].sort((a,b)=>b.date.localeCompare(a.date)||b.createdAt-a.createdAt).forEach(record=>{const item=document.createElement("li");item.className="record-item";const main=document.createElement("div");main.className="record-main";const title=document.createElement("strong");title.textContent=record.category;const detail=document.createElement("small");detail.textContent=`${record.date}${record.note?` · ${record.note}`:""}`;const amount=document.createElement("strong");amount.className=`record-amount ${record.type}`;amount.textContent=`${record.type==="income"?"+":"−"}${money(record.amount)}`;main.append(title,detail);item.append(main,amount);list.append(item)});const has=records.length>0;emptyState.hidden=has;clearButton.hidden=!has}
typeButtons.forEach(button=>button.addEventListener("click",()=>{entryType=button.dataset.type;typeButtons.forEach(item=>item.classList.toggle("active",item===button))}));
form.addEventListener("submit",event=>{event.preventDefault();const amount=Number(amountInput.value);if(!Number.isFinite(amount)||amount<=0)return;records.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:entryType,amount,category:categoryInput.value,date:dateInput.value,note:noteInput.value.trim(),createdAt:Date.now()});amountInput.value="";noteInput.value="";amountInput.focus();saveAndRender()});
clearButton.addEventListener("click",()=>{if(confirm("确定清空全部记账记录吗？")){records=[];saveAndRender()}});
if("serviceWorker" in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("sw.js"));
render();
